;; Package Manager
(try-load "config/packages/el-bundler")

;; Utility Package
;: (try-load "config/packages/powerline")
(try-load "config/packages/helm")
(try-load "config/packages/auto-async-byte-compile")
(try-load "config/packages/auto-complete")
(try-load "config/packages/elscreen")
(try-load "config/packages/emacs-w3m")
(try-load "config/packages/expand-region")
(try-load "config/packages/flex-autopair")
(try-load "config/packages/git-gutter")
(try-load "config/packages/goto-chg")
(try-load "config/packages/grep-edit")
(try-load "config/packages/jaunte")
(try-load "config/packages/multiple-cursors")
(try-load "config/packages/point-undo")
(try-load "config/packages/popwin")
(try-load "config/packages/popup")
(try-load "config/packages/redo")
(try-load "config/packages/navi2ch")
(try-load "config/packages/sequential-command")
(try-load "config/packages/smooth-scroll")
(try-load "config/packages/twittering-mode")
(try-load "config/packages/undohist")
(try-load "config/packages/uniquify")
(try-load "config/packages/yasnippet")
(try-load "config/packages/zlc")
(try-load "config/packages/multi-term")
(try-load "config/packages/auto-highlight-symbol")
(try-load "config/packages/google-translate")
(try-load "config/packages/rotate")
(try-load "config/packages/ace-jump-mode")
;; (try-load "config/packages/revive")
;; (try-load "config/packages/popup-pos-tip")
;; (try-load "config/packages/guide-key")
;; (try-load "config/packages/auto-save-buffers")
;; (try-load "config/packages/ediff")
;; (try-load "config/packages/quickrun")

;; Development Package
(try-load "config/packages/php-mode")
(try-load "config/packages/go-mode")
(try-load "config/packages/coffee-mode")
(try-load "config/packages/js2-mode")
(try-load "config/packages/web-mode")
(try-load "config/packages/scala-mode2")
(try-load "config/packages/yaml-mode")
(try-load "config/packages/scss-mode")
(try-load "config/packages/ruby-mode")
;; (try-load "config/packages/scheme-mode")
;; (try-load "config/packages/erlang-mode")

;; LocalConfig
(try-load "config/packages/local" t)
